/**
 * Blog articles: slug, category, date, titles, excerpts, body (blocks), relatedSlugs.
 * Body blocks: { type: 'h2'|'h3'|'p'|'ul'|'callout', text?, items?, title? }
 */
import { CATEGORY_IDS } from "./categories.js";

const articles = [
  {
    slug: "how-deposit-interest-is-taxed-armenia",
    category: "taxes-regulation",
    date: "2026-02-15",
    titleEn: "How Deposit Interest Is Taxed in Armenia",
    titleHy: "Ինչպես է հարկվում ավանդի տոկոսը Հայաստանում",
    excerptEn: "Interest from bank deposits in Armenia is subject to a 10% income tax, withheld at source. Here’s how it works and what you keep.",
    excerptHy: "Հայաստանի բանկային ավանդների տոկոսը հարկվում է 10% եկամտային հարկով՝ աղբյուրից պահումով: Ահա ինչպես է դա աշխատում:",
    relatedSlugs: ["how-armenian-banks-calculate-interest", "compound-interest-explained-for-savers"],
    bodyEn: [
      { type: "p", text: "If you earn interest on a deposit at an Armenian bank, that interest is taxable under Republic of Armenia (RA) law. Understanding how the tax applies helps you plan your savings and interpret the numbers you see in tools like the Saving.am calculator." },
      { type: "h2", text: "The 10% tax on interest income" },
      { type: "p", text: "Interest paid on bank deposits in Armenia is treated as income and is subject to a 10% income tax rate. This rate is set by RA tax legislation and applies to interest earned in AMD and in foreign currencies (e.g. USD, EUR) from accounts with Armenian banks." },
      { type: "callout", title: "Withheld at source", text: "Banks do not pay you the full gross interest. They withhold 10% and remit it to the tax authority, so you receive the net amount (90% of the interest) on your deposit. The calculator on Saving.am shows both gross interest, tax paid, and net interest so you can see your real return." },
      { type: "h2", text: "What you actually receive" },
      { type: "p", text: "When the bank credits interest to your account, the amount already has tax taken out. For example, if gross interest in a year is 100,000 AMD, the bank withholds 10,000 AMD in tax and you receive 90,000 AMD as net interest. Your final balance and any projections (e.g. in the Goal Planner) should be based on this net amount." },
      { type: "h3", text: "Does this apply to all deposits?" },
      { type: "p", text: "Yes. The 10% tax applies to interest earned on time deposits, accumulative (savings) deposits, and similar products offered by banks in Armenia, regardless of currency. There is no separate declaration needed for this interest when the bank withholds the tax." },
      { type: "h2", text: "Planning with tax in mind" },
      { type: "p", text: "When you compare banks or terms, always think in terms of after-tax returns. A higher advertised rate might still give you a better net return, but the 10% reduces every rate equally. Use the Saving.am calculator to see final balance and net interest after tax, and consider reading our article on how Armenian banks calculate interest to see how frequency of payment affects growth." },
      { type: "p", text: "Tax rules can change. For current rules and your personal situation, confirm with your bank or a tax advisor." },
    ],
    bodyHy: [
      { type: "p", text: "Եթե Հայաստանի բանկում ավանդի տոկոս եք ստանում, այդ տոկոսը ՀՀ օրենսդրությամբ հարկվող եկամուտ է: Հարկի կիրառումը հասկանալը կօգնի պլանավորել խնայողությունները և մեկնաբանել Saving.am հաշվիչի արդյունքները:" },
      { type: "h2", text: "10% հարկը տոկոսային եկամտի վրա" },
      { type: "p", text: "Հայաստանի բանկերում ավանդների վրա վճարվող տոկոսը համարվում է եկամուտ և հարկվում է 10% եկամտային հարկով: Այս դրույքը սահմանված է ՀՀ հարկային օրենսդրությամբ և կիրառվում է AMD-ով և արտարժույթով (USD, EUR) ավանդների տոկոսների նկատմամբ:" },
      { type: "callout", title: "Աղբյուրից պահում", text: "Բանկը ձեզ ամբողջ համախառն տոկոսը չի վճարում: Նա պահում է 10%-ը և փոխանցում հարկային մարմնին, այնպես որ դուք ստանում եք զուտ գումարը (տոկոսի 90%-ը): Saving.am հաշվիչը ցույց է տալիս և՛ համախառն տոկոսը, և՛ հարկը, և՛ զուտ տոկոսը:" },
      { type: "h2", text: "Ինչ եք իրականում ստանում" },
      { type: "p", text: "Երբ բանկը տոկոս է մուտքագրում ձեր հաշվին, գումարն արդեն հարկահանված է: Օրինակ, եթե տարեկան համախառն տոկոսը 100,000 ֏ է, բանկը պահում է 10,000 ֏ հարկ և դուք ստանում եք 90,000 ֏ զուտ տոկոս: Վերջնական մնացորդը և կանխատեսումները պետք է հիմնված լինեն այդ զուտ գումարի վրա:" },
      { type: "h3", text: "Կիրառվու՞մ է բոլոր ավանդների նկատմամբ" },
      { type: "p", text: "Այո: 10% հարկը կիրառվում է ժամկետային ավանդների, կուտակային ավանդների և Հայաստանի բանկերի նմանատիպ արտադրանքի տոկոսների նկատմամբ, անկախ արժույթից: Բանկի կողմից հարկի պահումի դեպքում առանձին հարկային հայտարարագիր ներկայացնելու կարիք չկա:" },
      { type: "h2", text: "Պլանավորում հարկը հաշվի առնելով" },
      { type: "p", text: "Երբ համեմատում եք բանկեր կամ պայմաններ, միշտ մտածեք հարկից հետո եկամտի մասին: Saving.am հաշվիչը ցույց է տալիս վերջնական մնացորդը և զուտ տոկոսը հարկից հետո: Հարկային կանոնները կարող են փոխվել; ձեր իրավիճակի համար հաստատեք ձեր բանկի կամ հարկային խորհրդատուի հետ:" },
    ],
  },
  {
    slug: "deposit-guarantee-explained",
    category: "guarantees-safety",
    date: "2026-02-14",
    titleEn: "Deposit Guarantee Explained: DGF and the 16 Million AMD Limit",
    titleHy: "Ավանդների երաշխիքը. ԴԵՀ և 16 միլիոն ֏ սահմանը",
    excerptEn: "The Deposit Guarantee Fund of Armenia protects your money up to 16,000,000 AMD per depositor per bank. Here’s how it works.",
    excerptHy: "Հայաստանի ավանդների երաշխիքային հիմնադրամը պաշտպանում է ձեր գումարը մինչև 16,000,000 ֏ մեկ ավանդատուի համար մեկ բանկում:",
    relatedSlugs: ["how-deposit-interest-is-taxed-armenia", "amd-vs-foreign-currency-deposits"],
    bodyEn: [
      { type: "p", text: "When you place money in an Armenian bank, it may be covered by the Deposit Guarantee Fund (DGF) of the Republic of Armenia. This system is designed to protect depositors if a member bank fails. Understanding the coverage limit and how it applies helps you make informed decisions about where and how much to save." },
      { type: "h2", text: "The 16 million AMD limit" },
      { type: "p", text: "The DGF guarantees deposits up to 16,000,000 Armenian drams (AMD) per depositor per bank. If a participating bank becomes unable to meet its obligations, eligible depositors can receive compensation up to this amount for their AMD deposits held at that bank. The limit is set by RA legislation and may be reviewed over time." },
      { type: "callout", title: "Per depositor, per bank", text: "Coverage is per person (or legal entity) and per bank. If you have 20 million AMD in one bank, only 16 million is guaranteed; the rest is at risk. If you split 20 million across two banks (e.g. 10 million in each), both amounts are fully covered. The Saving.am calculator warns you when your projected balance exceeds 16 million so you can consider splitting." },
      { type: "h2", text: "What is covered?" },
      { type: "p", text: "Typically, demand and time deposits in AMD at member banks are covered. Foreign currency deposits (USD, EUR, etc.) may be covered under the same or different rules—check the DGF or your bank for current details. Some products (e.g. certain investment or structured products) may be excluded." },
      { type: "h3", text: "Why it matters for savers" },
      { type: "p", text: "Knowing the limit helps you decide how much to keep in a single bank. If your goal is to grow savings beyond 16 million AMD, spreading amounts across several banks keeps each balance within the guarantee. Use the calculator’s guarantee warning and our article on AMD vs foreign currency deposits to plan accordingly." },
      { type: "p", text: "For the latest coverage rules and eligible institutions, refer to the official Deposit Guarantee Fund of Armenia and your bank." },
    ],
    bodyHy: [
      { type: "p", text: "Երբ գումար եք դնում հայկական բանկում, այն կարող է պաշտպանված լինել ՀՀ Ավանդների երաշխիքային հիմնադրամի (ԴԵՀ) կողմից: Այս համակարգը նախատեսված է ավանդատուներին պաշտպանելու համար, եթե անդամ բանկը սնանկանա:" },
      { type: "h2", text: "16 միլիոն ֏ սահմանը" },
      { type: "p", text: "ԴԵՀ-ն երաշխավորում է ավանդները մինչև 16,000,000 ֏ մեկ ավանդատուի համար մեկ բանկում: Եթե մասնակից բանկը չի կարողանում կատարել իր պարտավորությունները, իրավասու ավանդատուները կարող են փոխհատուցում ստանալ AMD ավանդների համար այդ բանկում: Սահմանը սահմանված է ՀՀ օրենսդրությամբ:" },
      { type: "callout", title: "Մեկ ավանդատու, մեկ բանկ", text: "Ծածկույթը հաշվարկվում է մեկ անձի (կամ իրավաբանական անձի) և մեկ բանկի համար: Եթե մի բանկում 20 միլիոն ֏ ունեք, երաշխավորված է միայն 16 միլիոնը: Եթե 20 միլիոնը բաժանեք երկու բանկի միջև, երկու գումարն էլ ամբողջությամբ ծածկված կլինեն: Saving.am հաշվիչը ձեզ զգուշացնում է, երբ կանխատեսվող մնացորդը գերազանցում է 16 միլիոնը:" },
      { type: "h2", text: "Ինչ է ծածկվում" },
      { type: "p", text: "Սովորաբար ծածկվում են AMD-ով պահանջային և ժամկետային ավանդները անդամ բանկերում: Արտարժույթային ավանդները (USD, EUR) կարող են ծածկվել նույն կամ այլ կանոններով: Իմացեք ԴԵՀ-ի և ձեր բանկի թարմացված տեղեկությունները:" },
      { type: "h3", text: "Ինչու է դա կարևոր" },
      { type: "p", text: "Սահմանը իմանալը օգնում է որոշել, թե որքան պահել մեկ բանկում: Եթե նպատակն է 16 միլիոնից ավելի խնայողություն, մի քանի բանկերի միջև բաշխելը յուրաքանչյուր մնացորդը պահում է երաշխիքի սահմաններում: Թարմ կանոնների համար դիմեք ԴԵՀ-ին և ձեր բանկին:" },
    ],
  },
  {
    slug: "how-armenian-banks-calculate-interest",
    category: "how-banks-work",
    date: "2026-02-13",
    titleEn: "How Armenian Banks Calculate Interest",
    titleHy: "Ինչպես են հայկական բանկերը հաշվարկում տոկոսը",
    excerptEn: "Banks use compound interest formulas and payment frequency to determine what you earn. Here’s a clear overview of how it works in Armenia.",
    excerptHy: "Բանկերը օգտագործում են բարդ տոկոսի բանաձևեր և վճարման հաճախականություն: Ահա թե ինչպես է դա աշխատում Հայաստանում:",
    relatedSlugs: ["interest-payment-frequency-explained", "compound-interest-explained-for-savers"],
    bodyEn: [
      { type: "p", text: "The interest you earn on an Armenian bank deposit depends on the stated annual rate, how often the bank pays or compounds interest, and the term of the deposit. Banks apply formulas that follow standard financial mathematics; understanding them helps you compare products and use tools like the Saving.am calculator correctly." },
      { type: "h2", text: "Annual rate and compounding" },
      { type: "p", text: "Banks typically quote an annual interest rate (e.g. 10% per year). The actual growth of your balance depends on how often interest is calculated and added. When interest is paid annually, the bank calculates 10% on the balance at the end of the year and adds it. When it is paid quarterly or monthly, each period uses the same annual rate converted to a per-period rate, and each payment is added to the balance, so the next period earns interest on a larger amount—this is compound interest." },
      { type: "h2", text: "The formula in practice" },
      { type: "p", text: "For a fixed term deposit with no top-ups, the standard compound formula is: final balance = principal × (1 + r/n)^(n×t), where r is the annual rate (as a decimal), n is the number of interest payments per year (1, 2, 4, or 12), and t is the term in years. Banks in Armenia may use slight variations (e.g. exact day count), but the idea is the same: more frequent compounding usually means slightly higher total interest." },
      { type: "callout", title: "Payment frequency matters", text: "A 10% annual rate paid once per year gives a different total than 10% paid monthly, because monthly payments compound more often. The Saving.am calculator lets you choose annual, semi-annual, quarterly, or monthly interest payment to match your product and see the effect." },
      { type: "h3", text: "With monthly top-ups" },
      { type: "p", text: "Many savers add a fixed amount each month. In that case, the bank (and our calculator) applies the same rate and frequency to the growing balance and to each new contribution from the month it is made. The result is a combination of compound growth on the initial deposit and on the stream of contributions." },
      { type: "p", text: "For exact terms and rounding rules, always refer to your bank’s contract and product conditions." },
    ],
    bodyHy: [
      { type: "p", text: "Հայկական բանկում ավանդի վրա ստացած տոկոսը կախված է տարեկան դրույքից, տոկոսի վճարման/կապիտալացման հաճախականությունից և ավանդի ժամկետից: Բանկերը կիրառում են ստանդարտ ֆինանսական մաթեմատիկայի բանաձևեր:" },
      { type: "h2", text: "Տարեկան դրույք և կապիտալացում" },
      { type: "p", text: "Բանկերը սովորաբար նշում են տարեկան տոկոսադրույք (օր. 10%): Մնացորդի աճը կախված է նրանից, թե որքան հաճախ է տոկոսը հաշվարկվում և ավելացվում: Տարեկան վճարման դեպքում բանկը հաշվարկում է 10%-ը տարվա վերջի մնացորդի վրա: Եռամսյակային կամ ամսական վճարման դեպքում յուրաքանչյուր period-ում օգտագործվում է նույն տարեկան դրույքը, և յուրաքանչյուր վճարում ավելացվում է մնացորդին—սա բարդ տոկոսն է:" },
      { type: "h2", text: "Բանաձևը գործնականում" },
      { type: "p", text: "Հաստատուն ժամկետային ավանդի համար ստանդարտ բանաձևն է՝ վերջնական մնացորդ = գլխավոր × (1 + r/n)^(n×t), որտեղ r-ը տարեկան դրույքն է, n-ը տոկոսի վճարումների թիվն է տարվա կտրվածքով (1, 2, 4 կամ 12), t-ը ժամկետն է տարիներով: Ավելի հաճախ կապիտալացումը սովորաբար տալիս է մի փոքր ավելի բարձր ընդհանուր տոկոս:" },
      { type: "callout", title: "Վճարման հաճախականությունը կարևոր է", text: "Saving.am հաշվիչում կարող եք ընտրել տարեկան, կիսամյակային, եռամսյակային կամ ամսական տոկոսի վճարում՝ ձեր արտադրանքին համապատասխան:" },
      { type: "h3", text: "Ամսական հավելումներով" },
      { type: "p", text: "Շատ խնայողներ ամիսը մի ֆիքսված գումար են ավելացնում: Այդ դեպքում բանկը (և մեր հաշվիչը) կիրառում է նույն դրույքն ու հաճախականությունը աճող մնացորդի և յուրաքանչյուր նոր մուծման նկատմամբ: Ճշգրիտ պայմանների համար դիմեք ձեր բանկի պայմանագրին:" },
    ],
  },
  {
    slug: "fixed-vs-accumulative-deposits",
    category: "products-terms",
    date: "2026-02-12",
    titleEn: "Fixed vs Accumulative Deposits",
    titleHy: "Ֆիքսված և կուտակային ավանդներ",
    excerptEn: "Time deposits lock your rate and term; accumulative deposits let you add money over time. Compare pros and cons for your goals.",
    excerptHy: "Ժամկետային ավանդը ֆիքսում է դրույքն ու ժամկետը; կուտակային ավանդը թույլ է տալիս ավելացնել գումար:",
    relatedSlugs: ["early-withdrawal-penalties-explained", "choosing-deposit-term-armenia"],
    bodyEn: [
      { type: "p", text: "Armenian banks offer different types of deposit products. Two common categories are fixed-term (time) deposits and accumulative (savings) deposits. The main difference is whether you commit a single sum for a fixed period or can add to the balance over time. Each has implications for interest rate, flexibility, and early withdrawal." },
      { type: "h2", text: "Fixed-term (time) deposits" },
      { type: "p", text: "You deposit a lump sum for a set period (e.g. 1, 2, or 5 years) at an agreed interest rate. The rate is usually fixed for the whole term. You typically cannot add more money to the same contract during the term. If you need the money early, the bank will usually apply an early withdrawal penalty (e.g. a reduced interest rate), so you get less than the projected amount. Fixed-term deposits often offer higher rates in exchange for this commitment." },
      { type: "h2", text: "Accumulative (savings) deposits" },
      { type: "p", text: "These allow you to add money periodically (e.g. monthly) in addition to the initial deposit. The balance grows with your contributions and with interest. Rates may be slightly lower than on fixed-term products, but the flexibility to top up can suit savers who want to build the habit of saving. Terms and conditions (e.g. minimum top-up, interest payment frequency) vary by bank; some products may allow partial withdrawals under certain rules." },
      { type: "callout", title: "Compare with the calculator", text: "Use the Saving.am calculator in Calculator mode for a fixed scenario, or add monthly top-ups to simulate an accumulative-style plan. Use Compare to see how a fixed deposit and a plan with monthly contributions differ in final balance and net interest." },
      { type: "h3", text: "Which to choose?" },
      { type: "p", text: "If you have a one-off sum and can lock it away, a fixed-term deposit may give a higher return. If you prefer to save regularly and grow the balance over time, an accumulative product may fit better. Consider early withdrawal penalties and the deposit guarantee limit (e.g. splitting large amounts across banks) in both cases. Read our articles on early withdrawal penalties and choosing the right deposit term for more detail." },
      { type: "p", text: "Product terms differ by bank; always confirm conditions with the bank before deciding." },
    ],
    bodyHy: [
      { type: "p", text: "Հայկական բանկերը առաջարկում են տարբեր ավանդային արտադրանքներ: Երկու տարածված տեսակ են ժամկետային (ֆիքսված) ավանդները և կուտակային ավանդները: Հիմնական տարբերությունը՝ մի գումար եք դնում ֆիքսված ժամկետով, թե կարող եք ժամանակի ընթացքում ավելացնել:" },
      { type: "h2", text: "Ժամկետային ավանդներ" },
      { type: "p", text: "Միանվագ գումար եք դնում սահմանված ժամկետով (օր. 1, 2 կամ 5 տարի) պայմանավորված տոկոսադրույքով: Դրույքը սովորաբար ֆիքսված է ամբողջ ժամկետի համար: Ժամկետից շուտ դուրս բերելու դեպքում բանկը սովորաբար կիրառում է տույժ:" },
      { type: "h2", text: "Կուտակային ավանդներ" },
      { type: "p", text: "Թույլ են տալիս պարբերաբար (օր. ամսական) ավելացնել գումար: Մնացորդը աճում է մուծումներով և տոկոսով: Դրույքները կարող են մի փոքր ցածր լինել, բայց հնարավորությունը ամսական ավելացնելը հարմար է խնայողություններ կուտակելու համար:" },
      { type: "callout", title: "Համեմատեք հաշվիչով", text: "Օգտագործեք Saving.am հաշվիչը՝ ամսական հավելումներով կուտակային պլան սիմուլյացիա անելու համար: Համեմատության ռեժիմում տեսեք ֆիքսված ավանդի և ամսական մուծումներով պլանի տարբերությունը:" },
      { type: "h3", text: "Ինչ ընտրել" },
      { type: "p", text: "Միանվագ գումար ունենալու և այն կողպելու դեպքում ժամկետային ավանդը կարող է ավելի բարձր եկամուտ տալ: Եթե ցանկանում եք պարբերաբար խնայել, կուտակային արտադրանքը ավելի հարմար կլինի: Պայմանները տարբեր են բանկից բանկ; հաստատեք ձեր բանկի հետ:" },
    ],
  },
  {
    slug: "early-withdrawal-penalties-explained",
    category: "products-terms",
    date: "2026-02-11",
    titleEn: "Early Withdrawal Penalties Explained",
    titleHy: "Վաղ դուրսբերման տույժերը մանրամասն",
    excerptEn: "Withdrawing your deposit before maturity usually means a lower interest rate is applied. Here’s how penalties work for AMD and FX deposits in Armenia.",
    excerptHy: "Ժամկետից շուտ ավանդը դուրս բերելը սովորաբար նշանակում է ավելի ցածր տոկոսադրույքի կիրառում:",
    relatedSlugs: ["fixed-vs-accumulative-deposits", "how-armenian-banks-calculate-interest"],
    bodyEn: [
      { type: "p", text: "When you open a fixed-term or accumulative deposit, you usually agree to keep the money until a certain date. If you need to withdraw earlier, the bank will typically apply a penalty—often by recalculating your interest at a lower rate. Understanding how this works helps you choose the right term and avoid surprises." },
      { type: "h2", text: "How the penalty is applied" },
      { type: "p", text: "A common approach in Armenian banks is to apply a penalty interest rate for the entire period from the start of the deposit to the withdrawal date. For example, if your contract rate is 10% per year and the early withdrawal penalty rate is 2%, the bank recalculates the interest you have \"earned\" as if the rate had been 2% all along. You then receive your principal plus this reduced interest (minus any tax), which can be noticeably less than the projected balance at the contractual rate." },
      { type: "callout", title: "Typical penalty rates", text: "In the Saving.am calculator we use indicative penalty rates: 2% per year for AMD deposits and 1.5% for USD and EUR. Actual penalties are set by each bank and stated in your contract—always check your bank’s terms." },
      { type: "h2", text: "Why banks use penalties" },
      { type: "p", text: "Banks use your deposit to fund lending and other activities. When you lock in a term, they can plan their liquidity. Early withdrawal creates a cost for the bank, so the penalty compensates for that and discourages early exit. The reduced rate is often still above zero, so you do not lose the principal, but you give up a large part of the interest you would have earned." },
      { type: "h3", text: "Planning to avoid early withdrawal" },
      { type: "p", text: "Choose a term that matches when you expect to need the money. If you are unsure, a shorter term or a product that allows partial withdrawals (if available) may be safer. Use the Early Withdrawal Simulator in the Saving.am calculator to see how much you would receive if you withdrew at different months, and read our article on choosing the right deposit term for more guidance." },
      { type: "p", text: "Penalty rules and rates vary by bank and product; your contract is the binding document." },
    ],
    bodyHy: [
      { type: "p", text: "Երբ բացում եք ժամկետային կամ կուտակային ավանդ, սովորաբար պայմանավորվում եք գումարը պահել մինչև որոշակի ամսաթիվ: Ժամկետից շուտ դուրս բերելու դեպքում բանկը սովորաբար կիրառում է տույժ՝ հաճախ տոկոսը վերահաշվարկելով ավելի ցածր դրույքով:" },
      { type: "h2", text: "Ինչպես է կիրառվում տույժը" },
      { type: "p", text: "Հայկական բանկերում տարածված մոտեցումը ավանդի սկզբից մինչև դուրսբերման ամսաթիվը ամբողջ ժամանակահատվածի համար կիրառել տույժային տոկոսադրույքն է: Օրինակ, եթե պայմանագրի դրույքը 10% է, իսկ վաղ դուրսբերման տույժը 2% է, բանկը վերահաշվարկում է ձեր \"վաստակած\" տոկոսը այնպես, կարծես դրույքը միշտ 2% էր: Դուք ստանում եք գլխավոր գումարն ու այդ կրճատված տոկոսը:" },
      { type: "callout", title: "Տիպիկ տույժային դրույքներ", text: "Saving.am հաշվիչում օգտագործվում են ցուցադրական տույժեր՝ AMD 2%, USD և EUR 1.5%: Փաստացի տույժերը սահմանում է յուրաքանչյուր բանկ և նշված են ձեր պայմանագրում:" },
      { type: "h2", text: "Ինչու են բանկերը կիրառում տույժեր" },
      { type: "p", text: "Բանկը ձեր ավանդն օգտագործում է վարկեր և այլ գործունեություն ֆինանսավորելու համար: Ժամկետը կողպելով՝ նրանք կարող են պլանավորել իրացվելիությունը: Վաղ դուրսբերումը բանկի համար ծախս է, hence տույժը փոխհատուցում է դա:" },
      { type: "h3", text: "Պլանավորում" },
      { type: "p", text: "Ընտրեք ժամկետ, որը համապատասխանում է, երբ ակնկալում եք գումարին կարիք ունենալ: Saving.am հաշվիչի Վաղ դուրսբերման սիմուլյատորում տեսեք, թե որքան կստանաք տարբեր ամիսներում դուրս բերելու դեպքում: Պայմանները տարբեր են բանկից բանկ:" },
    ],
  },
  {
    slug: "compound-interest-explained-for-savers",
    category: "education",
    date: "2026-02-10",
    titleEn: "Compound Interest Explained for Savers",
    titleHy: "Բարդ տոկոսը խնայողների համար",
    excerptEn: "Compound interest means earning interest on your interest. Here’s a simple guide to how it grows your savings over time.",
    excerptHy: "Բարդ տոկոսը նշանակում է տոկոս ստանալ ձեր տոկոսի վրա: Ահա պարզ ուղեցույց:",
    relatedSlugs: ["how-armenian-banks-calculate-interest", "how-to-use-saving-am-calculator"],
    bodyEn: [
      { type: "p", text: "Compound interest is one of the most powerful ideas in personal finance. Put simply: you earn interest on your initial deposit, and then you earn interest on that interest. Over time, this \"interest on interest\" effect can significantly increase your savings compared to simple interest, where you only earn on the original amount." },
      { type: "h2", text: "Simple vs compound interest" },
      { type: "p", text: "With simple interest, a 10% annual rate on 1,000,000 AMD always pays 100,000 AMD per year—only the principal earns. With compound interest, the first year you earn 100,000 AMD and it is added to your balance; the second year you earn 10% on 1,100,000 AMD (110,000 AMD), and so on. Each time the bank pays or credits interest, that amount becomes part of the balance that earns in the next period." },
      { type: "h2", text: "Frequency of compounding" },
      { type: "p", text: "The more often interest is paid and added to the balance, the stronger the compounding effect. Annual payment means one addition per year; quarterly means four; monthly means twelve. So a 10% rate paid monthly will yield slightly more by the end of the year than 10% paid once at the end, because each monthly payment starts earning interest in the following months. Our article on interest payment frequency goes into more detail." },
      { type: "callout", title: "Try it in the calculator", text: "Use the Saving.am calculator and switch between \"Interest paid\" options (annual, quarterly, monthly) with the same rate and term. You will see the final balance and net interest change as the compounding frequency changes." },
      { type: "h3", text: "Long-term impact" },
      { type: "p", text: "Over many years, the difference between simple and compound interest becomes large. That is why starting early and leaving money to compound, and adding regular contributions when possible, can build substantial savings. Remember that interest on Armenian bank deposits is subject to 10% tax, so the calculator shows net (after-tax) results. For more on tax, see how deposit interest is taxed in Armenia." },
      { type: "p", text: "Understanding compound interest helps you set realistic goals and compare deposit products fairly using tools like the Saving.am calculator." },
    ],
    bodyHy: [
      { type: "p", text: "Բարդ տոկոսը անձնական ֆինանսների ամենաուժեղ գաղափարներից մեկն է: Պարզ ասած՝ տոկոս եք ստանում սկզբնական ավանդի վրա, ապա տոկոս այդ տոկոսի վրա: Ժամանակի ընթացքում այս ազդեցությունը զգալիորեն ավելացնում է խնայողությունները՝ համեմատած պարզ տոկոսի հետ:" },
      { type: "h2", text: "Պարզ և բարդ տոկոս" },
      { type: "p", text: "Պարզ տոկոսով 10% տարեկան 1,000,000 ֏-ի վրա ամեն տարի 100,000 ֏ է վճարվում: Բարդ տոկոսով առաջին տարի 100,000 ֏ ավելանում է մնացորդին; երկրորդ տարի 10%-ը հաշվարկվում է 1,100,000 ֏-ի վրա (110,000 ֏) և այլն:" },
      { type: "h2", text: "Կապիտալացման հաճախականություն" },
      { type: "p", text: "Որքան հաճախ է տոկոսը վճարվում և ավելացվում մնացորդին, այնքան ամենաուժեղ է բարդ տոկոսի ազդեցությունը: Տարեկան վճարումը նշանակում է տարին մեկ ավելացում; ամսականը՝ տասներկու: Saving.am հաշվիչում փոխեք \"Տոկոսի վճարում\" (տարեկան, եռամսյակ, ամսական) և նույն դրույքով ու ժամկետով տեսեք վերջնական մնացորդի փոխվող արդյունքը:" },
      { type: "callout", title: "Փորձեք հաշվիչում", text: "Հայաստանի բանկային ավանդների տոկոսը հարկվում է 10%-ով; հաշվիչը ցույց է տալիս զուտ (հարկից հետո) արդյունքը: Ավելին՝ «Ինչպես է հարկվում ավանդի տոկոսը Հայաստանում»:" },
      { type: "h3", text: "Երկարաժամկետ ազդեցություն" },
      { type: "p", text: "Շատ տարիների ընթացքում պարզ և բարդ տոկոսի տարբերությունը մեծանում է: Բարդ տոկոսը հասկանալը օգնում է իրատեսական նպատակներ դնել և արդարացի համեմատել ավանդային արտադրանքները Saving.am հաշվիչով:" },
    ],
  },
  {
    slug: "choosing-deposit-term-armenia",
    category: "products-terms",
    date: "2026-02-09",
    titleEn: "Choosing the Right Deposit Term in Armenia",
    titleHy: "Ինչպես ընտրել ավանդի ժամկետը Հայաստանում",
    excerptEn: "Term length affects your rate and your flexibility. Short vs long: what to consider when choosing a deposit term in Armenian banks.",
    excerptHy: "Ժամկետի երկարությունը ազդում է դրույքի և ճկունության վրա: Կարճ ընդդեմ երկար ժամկետի:",
    relatedSlugs: ["early-withdrawal-penalties-explained", "fixed-vs-accumulative-deposits"],
    bodyEn: [
      { type: "p", text: "When you open a deposit at an Armenian bank, you usually choose a term: one year, two years, five years, or another period. The term affects the interest rate the bank offers and your ability to access the money without penalty. Choosing the right term is a balance between earning more and keeping flexibility." },
      { type: "h2", text: "Longer terms, often higher rates" },
      { type: "p", text: "Banks often offer higher interest rates for longer terms because they can use your money for a longer period. A five-year deposit might have a rate 1–2 percentage points above a one-year deposit. So if you are confident you will not need the funds before maturity, a longer term can increase your return." },
      { type: "h2", text: "The early withdrawal trade-off" },
      { type: "p", text: "If you withdraw before the end of the term, the bank will typically apply an early withdrawal penalty (e.g. recalculating interest at a lower rate). So locking in a long term for a higher rate has a cost: less flexibility. If your plans are uncertain, a shorter term or a product that allows partial access may be safer. Use the Early Withdrawal Simulator in the Saving.am calculator to see the impact of exiting at different times." },
      { type: "callout", title: "Match term to your goal", text: "Saving for a specific purchase in two years? A two-year term may fit. Building a long-term emergency fund? You might use a mix of terms or accumulative deposits so you are not locking everything for too long. The Goal Planner on Saving.am helps you work backwards from a target amount to see required deposits or contributions." },
      { type: "h3", text: "Renewal and inflation" },
      { type: "p", text: "Some deposits auto-renew at maturity. If rates have changed, the new rate may be different. Also consider inflation: a long fixed term locks in a nominal rate while purchasing power may change. The calculator’s inflation adjustment option shows real (inflation-adjusted) value of your projected balance. For more on product types, see fixed vs accumulative deposits." },
      { type: "p", text: "Terms and conditions vary by bank; confirm with your bank before deciding." },
    ],
    bodyHy: [
      { type: "p", text: "Հայկական բանկում ավանդ բացելիս սովորաբար ընտրում եք ժամկետ՝ մեկ, երկու, հինգ տարի կամ այլ: Ժամկետը ազդում է բանկի առաջարկած տոկոսադրույքի և գումարին առանց տույժի մուտք ունենալու ձեր հնարավորության վրա:" },
      { type: "h2", text: "Ավելի երկար ժամկետ, հաճախ ավելի բարձր դրույք" },
      { type: "p", text: "Բանկերը հաճախ ավելի բարձր տոկոս են առաջարկում ավելի երկար ժամկետի համար: Հինգ տարվա ավանդը կարող է 1–2 процентանոց բարձր դրույք ունենալ քան մեկ տարվա ավանդը:" },
      { type: "h2", text: "Վաղ դուրսբերման փոխզիջում" },
      { type: "p", text: "Ժամկետից շուտ դուրս բերելու դեպքում բանկը սովորաբար կիրառում է տույժ: Այսպիսով, ավելի երկար ժամկետ կողպելը ավելի բարձր դրույքի դիմաց նվազեցնում է ճկունությունը: Saving.am հաշվիչի Վաղ դուրսբերման սիմուլյատորում տեսեք տարբեր ամիսներում դուրս գալու ազդեցությունը:" },
      { type: "callout", title: "Ժամկետը նպատակին", text: "Երկու տարում կոնկրետ գնում? Երկու տարվա ժամկետը կարող է հարմար լինել: Նպատակի պլանավորիչը օգնում է նպատակային գումարից հակադարձ հաշվարկել անհրաժեշտ ավանդը կամ մուծումները:" },
      { type: "h3", text: "Թարմացում և գնաճ" },
      { type: "p", text: "Որոշ ավանդներ ժամկետի ավարտին ավտո-թարմացվում են: Գնաճի ճշգրտումը հաշվիչում ցույց է տալիս կանխատեսվող մնացորդի իրական (գնաճով ճշգրտված) արժեքը: Պայմանները տարբեր են բանկից բանկ:" },
    ],
  },
  {
    slug: "amd-vs-foreign-currency-deposits",
    category: "products-terms",
    date: "2026-02-08",
    titleEn: "AMD vs Foreign Currency Deposits: What to Consider",
    titleHy: "AMD և արտարժույթային ավանդներ. ինչ հաշվի առնել",
    excerptEn: "Armenian dram deposits often offer higher rates; FX deposits can reduce exchange-rate risk. Compare pros and cons for your situation.",
    excerptHy: "Դրամային ավանդները հաճախ ավելի բարձր դրույք են առաջարկում; արտարժույթը կարող է նվազեցնել կուրսի ռիսկը:",
    relatedSlugs: ["deposit-guarantee-explained", "how-deposit-interest-is-taxed-armenia"],
    bodyEn: [
      { type: "p", text: "Armenian banks offer deposits in Armenian drams (AMD) and in foreign currencies, mainly US dollars (USD) and euros (EUR). The choice affects the interest rate you get, the risk of exchange-rate changes, and how the deposit guarantee applies. Here is what to consider." },
      { type: "h2", text: "Interest rates: AMD vs FX" },
      { type: "p", text: "Historically, AMD deposit rates in Armenia have often been higher than USD or EUR rates. That is because the central bank’s policy rate and local currency conditions influence AMD rates, while FX rates are more aligned with global conditions and the bank’s cost of foreign funding. So if you are willing to hold local currency, you may earn more interest in AMD—but you take on exchange-rate risk if you later need to convert to another currency." },
      { type: "h2", text: "Exchange-rate risk" },
      { type: "p", text: "If you save in AMD and the dram weakens against the dollar or euro, the purchasing power of your savings in terms of foreign goods or travel can fall. Saving in USD or EUR can protect you against dram depreciation if your future expenses are in those currencies. There is no free lunch: FX deposits usually offer lower interest, so the trade-off is stability vs return." },
      { type: "callout", title: "Deposit guarantee", text: "The Deposit Guarantee Fund of Armenia guarantees up to 16,000,000 AMD per depositor per bank for AMD deposits. Coverage for foreign currency deposits may be defined differently (e.g. in AMD equivalent or in the same currency)—check the DGF and your bank for current rules. See our article on the deposit guarantee for more." },
      { type: "h3", text: "Tax and early withdrawal" },
      { type: "p", text: "Interest on both AMD and FX deposits is subject to the 10% income tax in Armenia, withheld at source. Early withdrawal penalties may differ by currency; the Saving.am calculator uses typical rates (e.g. 2% for AMD, 1.5% for USD/EUR) for illustration. Your bank’s contract will state the exact penalty. Use the calculator to compare scenarios in AMD, USD, and EUR and see final balance and net interest for each." },
      { type: "p", text: "Your choice should depend on your income, expenses, and risk tolerance. For current rates and product details, always check with your bank." },
    ],
    bodyHy: [
      { type: "p", text: "Հայկական բանկերը առաջարկում են ավանդներ հայկական դրամով (AMD) և արտարժույթով (USD, EUR): Ընտրությունը ազդում է տոկոսադրույքի, կուրսի փոփոխության ռիսկի և ավանդի երաշխիքի կիրառման վրա:" },
      { type: "h2", text: "Տոկոսադրույքներ. AMD ընդդեմ արտարժույթի" },
      { type: "p", text: "Պատմականորեն AMD ավանդների դրույքները Հայաստանում հաճախ ավելի բարձր են եղել քան USD կամ EUR-ի դրույքները: Եթե պատրաստ եք պահել տեղական արժույթ, կարող եք ավելի շատ տոկոս ստանալ AMD-ով, բայց կուրսի ռիսկ կա:" },
      { type: "h2", text: "Կուրսի ռիսկ" },
      { type: "p", text: "AMD-ով խնայելիս, եթե դրամը թուլանա դոլարի կամ եվրոյի նկատմամբ, խնայողությունների գնողունակությունը կարող է նվազել: USD կամ EUR-ով խնայելը կարող է պաշտպանել դրամի արժեզրկումից, եթե ապագա ծախսերը այդ արժույթներով են: Արտարժույթային ավանդները սովորաբար ավելի ցածր տոկոս են տալիս:" },
      { type: "callout", title: "Ավանդի երաշխիք", text: "ԴԵՀ-ն երաշխավորում է մինչև 16,000,000 ֏ մեկ ավանդատուի համար AMD ավանդների համար: Արտարժույթային ավանդների ծածկույթը կարող է այլ կերպ սահմանված լինել: Իմացեք ԴԵՀ-ի և ձեր բանկի կանոնները:" },
      { type: "h3", text: "Հարկ և վաղ դուրսբերում" },
      { type: "p", text: "Ե՛թ AMD, ե՛թ արտարժույթային ավանդների տոկոսը Հայաստանում հարկվում է 10%-ով: Վաղ դուրսբերման տույժերը կարող են տարբեր լինել արժույթով: Saving.am հաշվիչում համեմատեք AMD, USD և EUR սցենարները: Ընտրությունը կախված է եկամուտից, ծախսերից և ռիսկի նկատմամբ հանդուրժողականությունից:" },
    ],
  },
  {
    slug: "interest-payment-frequency-explained",
    category: "how-banks-work",
    date: "2026-02-07",
    titleEn: "Understanding Interest Payment Frequency (Annual, Quarterly, Monthly)",
    titleHy: "Տոկոսի վճարման հաճախականությունը. տարեկան, եռամսյակ, ամսական",
    excerptEn: "Interest can be paid once a year, every quarter, or every month. How does payment frequency affect your total return?",
    excerptHy: "Տոկոսը կարող է վճարվել տարեկան մեկ, եռամսյակային կամ ամսական: Ինչպես է հաճախականությունը ազդում ընդհանուր եկամտի վրա:",
    relatedSlugs: ["how-armenian-banks-calculate-interest", "compound-interest-explained-for-savers"],
    bodyEn: [
      { type: "p", text: "When you compare deposit offers from Armenian banks, you will see not only different interest rates but also different interest payment frequencies. Some products pay interest once a year; others every six months, every quarter, or every month. The frequency affects how much you actually earn because of compounding." },
      { type: "h2", text: "What is payment frequency?" },
      { type: "p", text: "Payment frequency is how often the bank calculates and credits interest to your account. \"Annually\" means once per year (e.g. at the end of the 12th month). \"Quarterly\" means four times per year; \"monthly\" means twelve times. When interest is credited, it usually becomes part of your balance for the next period, so you then earn interest on that larger balance—that is compound interest." },
      { type: "h2", text: "Why frequency changes your return" },
      { type: "p", text: "With the same annual rate, more frequent payment means more compounding. For example, 10% per year paid at the end of the year gives you one compounding step. The same 10% paid monthly means twelve smaller steps: each month you earn a bit of interest, it is added, and the next month you earn on the new balance. So by the end of the year, the total interest with monthly payment is slightly higher than with annual payment. The difference is usually modest for one year but grows over longer terms." },
      { type: "callout", title: "Compare in the calculator", text: "In the Saving.am calculator, use the \"Interest paid\" bar to switch between Annual, Semi-annual, Quarterly, and Monthly. Keep the same initial deposit, rate, and term; only change the frequency. You will see the final balance and net interest increase as you move from annual to monthly." },
      { type: "h3", text: "What to look for in a product" },
      { type: "p", text: "When choosing a deposit, check the contract for how often interest is paid and whether it is added to the balance (capitalized) or paid out to a separate account. If it is capitalized, more frequent payment means more compounding. Also consider your cash-flow needs: monthly interest might suit you if you want regular income, while annual payment might suit long-term growth. For the math behind it, see how Armenian banks calculate interest and compound interest explained for savers." },
      { type: "p", text: "Product terms vary by bank; confirm the exact frequency and capitalization rules with your bank." },
    ],
    bodyHy: [
      { type: "p", text: "Հայկական բանկերի ավանդային առաջարկները համեմատելիս կտեսնեք ոչ միայն տարբեր տոկոսադրույքներ, այլև տոկոսի վճարման տարբեր հաճախականություններ: Որոշ արտադրանքներ տոկոս են վճարում տարեկան մեկ, այլները՝ եռամսյակային կամ ամսական: Հաճախականությունը ազդում է կապիտալացման շնորհիվ իրականում վաստակած գումարի վրա:" },
      { type: "h2", text: "Ինչ է վճարման հաճախականությունը" },
      { type: "p", text: "Վճարման հաճախականությունը այն է, թե որքան հաճախ է բանկը հաշվարկում և մուտքագրում տոկոսը: «Տարեկան» նշանակում է տարին մեկ; «Եռամսյակային»՝ տարին չորս անգամ; «Ամսական»՝ տասներկու: Տոկոսը մուտքագրվելիս սովորաբար դառնում է հաջորդ period-ի մնացորդի մաս՝ սա բարդ տոկոսն է:" },
      { type: "h2", text: "Ինչու հաճախականությունը փոխում է եկամուտը" },
      { type: "p", text: "Նույն տարեկան դրույքով ավելի հաճախ վճարումը նշանակում է ավելի շատ կապիտալացում: 10% տարեկան ամսական վճարման դեպքում տարվա վերջում ընդհանուր տոկոսը մի փոքր ավելի բարձր կլինի քան տարեկան մեկ վճարման: Տարբերությունը մեկ տարվա համար սովորաբար համեստ է, բայց աճում է ավելի երկար ժամկետներում:" },
      { type: "callout", title: "Համեմատեք հաշվիչում", text: "Saving.am հաշվիչում օգտագործեք «Տոկոսի վճարում» սանդղակը՝ Տարեկան, Կիսամյակ, Եռամսյակ, Ամսական ընտրելու համար: Նույն ավանդը, դրույքը և ժամկետը պահելով փոխեք միայն հաճախականությունը: Կտեսնեք վերջնական մնացորդի և զուտ տոկոսի աճը:" },
      { type: "h3", text: "Ինչ փնտրել արտադրանքում" },
      { type: "p", text: "Ավանդ ընտրելիս պայմանագրում ստուգեք, որքան հաճախ է տոկոսը վճարվում և արդյոք այն ավելացվում է մնացորդին (կապիտալացվում), թե վճարվում այլ հաշվի: Պայմանները տարբեր են բանկից բանկ:" },
    ],
  },
  {
    slug: "how-to-use-saving-am-calculator",
    category: "education",
    date: "2026-02-06",
    titleEn: "How to Use the Saving.am Deposit Calculator",
    titleHy: "Ինչպես օգտվել Saving.am ավանդի հաշվիչից",
    excerptEn: "A short guide to the Saving.am compound interest calculator: Calculator, Goal Planner, Compare, and key settings.",
    excerptHy: "Saving.am բարդ տոկոսի հաշվիչի համառոտ ուղեցույց. Հաշվիչ, Նպատակի պլանավորիչ, Համեմատություն:",
    relatedSlugs: ["compound-interest-explained-for-savers", "how-armenian-banks-calculate-interest"],
    bodyEn: [
      { type: "p", text: "The Saving.am calculator helps you estimate how your savings can grow with compound interest, tax, and optional monthly top-ups. It is designed for the Armenian bank market and supports AMD, USD, and EUR. Here is how to use its main features." },
      { type: "h2", text: "Calculator tab" },
      { type: "p", text: "Enter your initial deposit amount, choose a bank (or custom rate), and set the term (e.g. 1–10 years). You can add a monthly top-up and choose how many months you will add it (e.g. all 12 or only the first 6). Select how often interest is paid: annually, semi-annually, quarterly, or monthly. The calculator shows final balance, total contributed, net interest (after 10% tax), and effective yield. It also shows a yearly breakdown table and charts. If your projected balance exceeds 16 million AMD, a warning reminds you about the deposit guarantee limit." },
      { type: "h2", text: "Early withdrawal simulator" },
      { type: "p", text: "In the same tab, use the \"Early withdrawal\" section to see what would happen if you withdrew at a specific month. The tool applies a penalty rate (e.g. 2% for AMD, 1.5% for USD/EUR) and shows the balance you would receive and the interest lost compared to holding to maturity." },
      { type: "h2", text: "Goal Planner tab" },
      { type: "p", text: "Work backwards from a target amount. You can find: how many years to reach your goal with a given rate and monthly top-up; the initial deposit needed to reach the goal in a set time; or the monthly contribution needed to reach the goal. Enter the target balance, interest rate, and optional existing monthly contribution, then choose the mode that matches your question." },
      { type: "h2", text: "Compare tab" },
      { type: "p", text: "Set up two scenarios side by side (e.g. different banks, rates, or terms). You see the final balance and net profit for each, so you can compare strategies at a glance. Useful for deciding between a higher rate with a longer term and a lower rate with more flexibility." },
      { type: "callout", title: "Disclaimer", text: "The calculator is for estimation and education only. Bank rates, terms, and tax rules change. Always confirm with your bank and consider professional advice for important decisions. For more on the concepts behind the numbers, read compound interest explained and how Armenian banks calculate interest." },
      { type: "p", text: "Explore the tabs and settings to see how different choices affect your savings growth. We hope it helps you plan with confidence." },
    ],
    bodyHy: [
      { type: "p", text: "Saving.am հաշվիչը օգնում է գնահատել, թե ինչպես կարող են աճել խնայողությունները բարդ տոկոսով, հարկով և ամսական հավելումներով: Նախատեսված է հայկական բանկային շուկայի համար, աջակցում է AMD, USD և EUR:" },
      { type: "h2", text: "Հաշվիչ ներդիր" },
      { type: "p", text: "Մուտքագրեք սկզբնական ավանդը, ընտրեք բանկ (կամ սեփական դրույք), սահմանեք ժամկետ (1–10 տարի): Կարող եք ավելացնել ամսական հավելում և ընտրել, քանի ամիս (օր. բոլոր 12 կամ առաջին 6): Ընտրեք տոկոսի վճարման հաճախականությունը: Հաշվիչը ցույց է տալիս վերջնական մնացորդը, ընդհանուր մուծվածը, զուտ տոկոսը (10% հարկից հետո) և արդյունավետ եկամտաբերությունը: Եթե մնացորդը գերազանցում է 16 միլիոն ֏-ը, ցուցադրվում է երաշխիքի զգուշացում:" },
      { type: "h2", text: "Վաղ դուրսբերման սիմուլյատոր" },
      { type: "p", text: "Նույն ներդիրում «Վաղ դուրսբերում» բաժնում տեսեք, թե ինչ կլինի, եթե դուրս բերեք կոնկրետ ամսում: Կիրառվում է տույժային դրույք (օր. AMD 2%, USD/EUR 1.5%):" },
      { type: "h2", text: "Նպատակի պլանավորիչ" },
      { type: "p", text: "Աշխատեք նպատակային գումարից հակադարձ: Կարող եք պարզել՝ քանի տարի է անհրաժեշտ նպատակին հասնելու համար; ինչ սկզբնական ավանդ է անհրաժեշտ; կամ ինչ ամսական մուծում է անհրաժեշտ:" },
      { type: "h2", text: "Համեմատություն" },
      { type: "p", text: "Կողք-կողքի դրեք երկու սցենար (տարբեր բանկեր, դրույքներ, ժամկետներ): Տեսնում եք յուրաքանչյուրի վերջնական մնացորդն ու զուտ շահույթը: Հաշվիչը միայն գնահատման և կրթական նպատակով է: Միշտ հաստատեք ձեր բանկի հետ:" },
      { type: "callout", title: "Ծանուցում", text: "Ավելին՝ բարդ տոկոսը և ինչպես են հայկական բանկերը հաշվարկում տոկոսը: Փորձեք ներդիրները և կարգավորումները:" },
    ],
  },
];

// Validate categories
articles.forEach((a) => {
  if (!CATEGORY_IDS.includes(a.category)) throw new Error(`Unknown category: ${a.category}`);
});

export default articles;
